spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eureka?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  application:
    name: productserver
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler: 1.0


server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://127.0.0.1:8100/eureka , http://127.0.0.1:8101/eureka , http://127.0.0.1:8102/eureka , http://127.0.0.1:8103/eureka
      defaultZone: http://127.0.0.1:8200/eureka,http://127.0.0.1:8201/eureka
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG  #sleuth框架下的所有的日志级别是debug
